export const CELL_CREATE_REQUEST = 'CELL_CREATE_REQUEST'
export const CELL_CREATE_SUCCESS = 'CELL_CREATE_SUCCESS'
export const CELL_CREATE_FAIL = 'CELL_CREATE_FAIL'
export const CELL_CREATE_RESET = 'CELL_CREATE_RESET'

export const CELL_LIST_REQUEST = 'CELL_LIST_REQUEST'
export const CELL_LIST_SUCCESS = 'CELL_LIST_SUCCESS'
export const CELL_LIST_FAIL = 'CELL_LIST_FAIL'

export const CELL_DETAILS_REQUEST = 'CELL_DETAILS_REQUEST'
export const CELL_DETAILS_SUCCESS = 'CELL_DETAILS_SUCCESS'
export const CELL_DETAILS_FAIL = 'CELL_DETAILS_FAIL'

export const CELL_DELETE_REQUEST = 'CELL_DELETE_REQUEST'
export const CELL_DELETE_SUCCESS = 'CELL_DELETE_SUCCESS'
export const CELL_DELETE_FAIL = 'CELL_DELETE_FAIL'

export const CELL_EDIT_REQUEST = 'CELL_EDIT_REQUEST'
export const CELL_EDIT_SUCCESS = 'CELL_EDIT_SUCCESS'
export const CELL_EDIT_FAIL = 'CELL_EDIT_FAIL'
export const CELL_EDIT_RESET = 'CELL_EDIT_RESET'
