export const OAUTH_USER_REGISTER_REQUEST = 'OAUTH_USER_REGISTER_REQUEST'
export const OAUTH_USER_REGISTER_SUCCESS = 'OAUTH_USER_REGISTER_SUCCESS'
export const OAUTH_USER_REGISTER_FAIL = 'OAUTH_USER_REGISTER_FAIL'

export const OAUTH_USER_LOGOUT_REQUEST = 'OAUTH_USER_LOGOUT_REQUEST'
export const OAUTH_USER_LOGOUT_SUCCESS = 'OAUTH_USER_LOGOUT_SUCCESS'
export const OAUTH_USER_LOGOUT_FAIL = 'OAUTH_USER_LOGOUT_FAIL'
