/////////////////////////////////////
//////// CELL PHONE CONSTANTS ///////

export const CELL_CREATE_REQUEST = 'CELL_CREATE_REQUEST'
export const CELL_CREATE_SUCCESS = 'CELL_CREATE_SUCCESS'
export const CELL_CREATE_FAIL = 'CELL_CREATE_FAIL'
export const CELL_CREATE_RESET = 'CELL_CREATE_RESET'

export const CELL_LIST_REQUEST = 'CELL_LIST_REQUEST'
export const CELL_LIST_SUCCESS = 'CELL_LIST_SUCCESS'
export const CELL_LIST_FAIL = 'CELL_LIST_FAIL'

export const CELL_DETAILS_REQUEST = 'CELL_DETAILS_REQUEST'
export const CELL_DETAILS_SUCCESS = 'CELL_DETAILS_SUCCESS'
export const CELL_DETAILS_FAIL = 'CELL_DETAILS_FAIL'

export const CELL_DELETE_REQUEST = 'CELL_DELETE_REQUEST'
export const CELL_DELETE_SUCCESS = 'CELL_DELETE_SUCCESS'
export const CELL_DELETE_FAIL = 'CELL_DELETE_FAIL'

export const CELL_EDIT_REQUEST = 'CELL_EDIT_REQUEST'
export const CELL_EDIT_SUCCESS = 'CELL_EDIT_SUCCESS'
export const CELL_EDIT_FAIL = 'CELL_EDIT_FAIL'
export const CELL_EDIT_RESET = 'CELL_EDIT_RESET'

//////////////////////////////
//////// TV CONSTANTS ///////

export const TV_CREATE_REQUEST = 'TV_CREATE_REQUEST'
export const TV_CREATE_SUCCESS = 'TV_CREATE_SUCCESS'
export const TV_CREATE_FAIL = 'TV_CREATE_FAIL'
export const TV_CREATE_RESET = 'TV_CREATE_RESET'

export const TV_LIST_REQUEST = 'TV_LIST_REQUEST'
export const TV_LIST_SUCCESS = 'TV_LIST_SUCCESS'
export const TV_LIST_FAIL = 'TV_LIST_FAIL'

export const TV_DETAILS_REQUEST = 'TV_DETAILS_REQUEST'
export const TV_DETAILS_SUCCESS = 'TV_DETAILS_SUCCESS'
export const TV_DETAILS_FAIL = 'TV_DETAILS_FAIL'

export const TV_DELETE_REQUEST = 'TV_DELETE_REQUEST'
export const TV_DELETE_SUCCESS = 'TV_DELETE_SUCCESS'
export const TV_DELETE_FAIL = 'TV_DELETE_FAIL'

export const TV_EDIT_REQUEST = 'TV_EDIT_REQUEST'
export const TV_EDIT_SUCCESS = 'TV_EDIT_SUCCESS'
export const TV_EDIT_FAIL = 'TV_EDIT_FAIL'
export const TV_EDIT_RESET = 'TV_EDIT_RESET'

///////////////////////////////////
//////// Computer CONSTANTS ///////

export const COMPUTER_CREATE_REQUEST = 'COMPUTER_CREATE_REQUEST'
export const COMPUTER_CREATE_SUCCESS = 'COMPUTER_CREATE_SUCCESS'
export const COMPUTER_CREATE_FAIL = 'COMPUTER_CREATE_FAIL'
export const COMPUTER_CREATE_RESET = 'COMPUTER_CREATE_RESET'

export const COMPUTER_LIST_REQUEST = 'COMPUTER_LIST_REQUEST'
export const COMPUTER_LIST_SUCCESS = 'COMPUTER_LIST_SUCCESS'
export const COMPUTER_LIST_FAIL = 'COMPUTER_LIST_FAIL'

export const COMPUTER_DETAILS_REQUEST = 'COMPUTER_DETAILS_REQUEST'
export const COMPUTER_DETAILS_SUCCESS = 'COMPUTER_DETAILS_SUCCESS'
export const COMPUTER_DETAILS_FAIL = 'COMPUTER_DETAILS_FAIL'

export const COMPUTER_DELETE_REQUEST = 'COMPUTER_DELETE_REQUEST'
export const COMPUTER_DELETE_SUCCESS = 'COMPUTER_DELETE_SUCCESS'
export const COMPUTER_DELETE_FAIL = 'COMPUTER_DELETE_FAIL'

export const COMPUTER_EDIT_REQUEST = 'COMPUTER_EDIT_REQUEST'
export const COMPUTER_EDIT_SUCCESS = 'COMPUTER_EDIT_SUCCESS'
export const COMPUTER_EDIT_FAIL = 'COMPUTER_EDIT_FAIL'
export const COMPUTER_EDIT_RESET = 'COMPUTER_EDIT_RESET'

///////////////////////////////////
//////// ACCESSORY CONSTANTS ///////

export const ACCESSORY_CREATE_REQUEST = 'ACCESSORY_CREATE_REQUEST'
export const ACCESSORY_CREATE_SUCCESS = 'ACCESSORY_CREATE_SUCCESS'
export const ACCESSORY_CREATE_FAIL = 'ACCESSORY_CREATE_FAIL'
export const ACCESSORY_CREATE_RESET = 'ACCESSORY_CREATE_RESET'

export const ACCESSORY_LIST_REQUEST = 'ACCESSORY_LIST_REQUEST'
export const ACCESSORY_LIST_SUCCESS = 'ACCESSORY_LIST_SUCCESS'
export const ACCESSORY_LIST_FAIL = 'ACCESSORY_LIST_FAIL'

export const ACCESSORY_DETAILS_REQUEST = 'ACCESSORY_DETAILS_REQUEST'
export const ACCESSORY_DETAILS_SUCCESS = 'ACCESSORY_DETAILS_SUCCESS'
export const ACCESSORY_DETAILS_FAIL = 'ACCESSORY_DETAILS_FAIL'

export const ACCESSORY_DELETE_REQUEST = 'ACCESSORY_DELETE_REQUEST'
export const ACCESSORY_DELETE_SUCCESS = 'ACCESSORY_DELETE_SUCCESS'
export const ACCESSORY_DELETE_FAIL = 'ACCESSORY_DELETE_FAIL'

export const ACCESSORY_EDIT_REQUEST = 'ACCESSORY_EDIT_REQUEST'
export const ACCESSORY_EDIT_SUCCESS = 'ACCESSORY_EDIT_SUCCESS'
export const ACCESSORY_EDIT_FAIL = 'ACCESSORY_EDIT_FAIL'
export const ACCESSORY_EDIT_RESET = 'ACCESSORY_EDIT_RESET'

///////////////////////////////////
//////// PRODUCT CONSTANTS ///////

export const GET_RECENT_PRODUCT_REQUEST = 'GET_RECENT_PRODUCT_REQUEST'
export const GET_RECENT_PRODUCT_SUCCESS = 'GET_RECENT_PRODUCT_SUCCESS'
export const GET_RECENT_PRODUCT_FAIL = 'GET_RECENT_PRODUCT_FAIL'
