export const TV_CREATE_REQUEST = 'TV_CREATE_REQUEST'
export const TV_CREATE_SUCCESS = 'TV_CREATE_SUCCESS'
export const TV_CREATE_FAIL = 'TV_CREATE_FAIL'
export const TV_CREATE_RESET = 'TV_CREATE_RESET'

export const TV_LIST_REQUEST = 'TV_LIST_REQUEST'
export const TV_LIST_SUCCESS = 'TV_LIST_SUCCESS'
export const TV_LIST_FAIL = 'TV_LIST_FAIL'

export const TV_DETAILS_REQUEST = 'TV_DETAILS_REQUEST'
export const TV_DETAILS_SUCCESS = 'TV_DETAILS_SUCCESS'
export const TV_DETAILS_FAIL = 'TV_DETAILS_FAIL'

export const TV_DELETE_REQUEST = 'TV_DELETE_REQUEST'
export const TV_DELETE_SUCCESS = 'TV_DELETE_SUCCESS'
export const TV_DELETE_FAIL = 'TV_DELETE_FAIL'

export const TV_EDIT_REQUEST = 'TV_EDIT_REQUEST'
export const TV_EDIT_SUCCESS = 'TV_EDIT_SUCCESS'
export const TV_EDIT_FAIL = 'TV_EDIT_FAIL'
export const TV_EDIT_RESET = 'TV_EDIT_RESET'
